title: Biopragmatics
author: Charles Tapley Hoyt
email: cthoyt@gmail.com
description: >
  This site describes my research, teaching, mentorship, and future plans.

twitter_username: cthoytp
github_username:  cthoyt
linkedin_username: cthoyt

theme: minima
plugins:
  - jekyll-feed
