title: Biopragmatics
author: Charles Tapley Hoyt
email: cthoyt@gmail.com
description: >
  Unraveling complex biology using knowledge graph embeddings

twitter_username: cthoytp
github_username:  cthoyt
linkedin_username: cthoyt

theme: minima
plugins:
  - jekyll-feed
