title: Biopragmatics
author: Charles Tapley Hoyt
email: cthoyt@gmail.com
description: >
  Unraveling complex biology with biological knowledge graphs

twitter_username: cthoyt
github_username:  cthoyt
linkedin_username: cthoyt

url: "https://cthoyt.com"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
